pipeline{
    agent any
    stages{
        stage("clean install"){
            steps{
                withMaven(maven : Maven){
                sh 'mvn clean install'
                }
            }
            
        }
        stage("Build docker image"){
            steps{
                withDocker(docker : Docker){
                    sh 'docker build -t my-app .'
                }
            }
            
        }
    }
    
}
